### ISSUE TITLE
Logo creation tools

### ISSUE THREAD

**Issue by karllhughes** [karllhughes/side-project-marketing#31]
I'm working on a list of logo creation tools to supplement [those on the list already](https://www.sideprojectchecklist.com/marketing-checklist/#logo-creation-tools). If you use any logo creation or analysis tools that might be helpful, feel free to add them to this issue.

**Comment by vikeen** [comment]
https://logojoy.com/

**Comment by atherdon** [comment]
I like logojoy, one time I was nominated to top10, but on this list, i would prefer free options first. 
Like tool it's awesome. Would i use it for side projects: no. because I want to be lean as i can, so spend on the logo, like on design - it will be at the end of my list

The easiest way with logos - just have included Google font and write company name or startup name

Next important thing: what file format it return and will you be able to generate a favicon, icon for facebook page, etc.

**LogoFox** from this list have the most cheap options($1).

I used logodust twice. But they have an issue: sometimes you'll get png, sometimes svg file.

this can be added to list:
http://logodust.com/
http://freeminimallogos.com/
http://logodust.com
http://www.logomakerapp.com

**Comment by karllhughes** [comment]
Thanks for all the suggestions! You can see them and more: https://www.sideprojectchecklist.com/2017/logos/

Also, to add other ideas, submit them here: https://airtable.com/shrwrPOxd0wlqoiZb
